"use client"
import { ThemeProvider } from "@gravity-ui/uikit"
import Image from 'next/image'

import "@gravity-ui/uikit/styles/fonts.css"
import "@gravity-ui/uikit/styles/styles.css"
import "./layout.css"
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

enum Roles {
    Admin,
    Mentor,
    Student
}

interface UserProps {
    name: string;
    role: Roles;
    image: string;
}

const getUserRole = (): Roles => {
    return Roles.Admin
}

const getUserProps = (): UserProps => {
    return {
        name: 'Иван Иванов',
        role: getUserRole(),
        image: 'avatar.svg'
    }
}

const UserPanel: React.FC = () => {
    const props: UserProps = getUserProps()

    const getRoleStyles = (role: Roles) => {
        switch (role) {
            case Roles.Student:
                return {
                    displayRoleName: 'Студент',
                    backgroundColor: '#D4A0FF',
                    color: '#4F1C7B',
                }
            case Roles.Mentor:
                return {
                    displayRoleName: 'Ментор',
                    backgroundColor: '#34B5FA33',
                    color: '#34B5FA',
                }
            case Roles.Admin:
                return {
                    displayRoleName: 'Администратор',
                    backgroundColor: '#FF9E9E',
                    color: '#D50000',
                }
            default:
                return {
                    displayRoleName: 'Аноним',
                    backgroundColor: '#f5f5f5',
                    color: '#000000',
                }
        }
    }

    const roleStyles = getRoleStyles(props.role)

    return (
        <div style={{ display: 'flex', flexDirection: 'row', gap: '8px', alignItems: 'center' }}>
            <div style={{ display: 'flex', flexDirection: 'column', margin: 0, marginRight: '12px', textAlign: 'right' }}>
                <div style={{ fontSize: '14px', fontWeight: '600' }}>{props.name}</div>

                <div>
                    <div style={{
                        display: 'inline-block',
                        backgroundColor: roleStyles.backgroundColor,
                        color: roleStyles.color,
                        padding: '4px 8px',
                        borderRadius: '12px',
                        fontWeight: 'bold',
                        fontSize: '12px',
                        lineHeight: '15px',
                        letterSpacing: '0.5px',
                        textTransform: 'uppercase',
                    }}>
                        {roleStyles.displayRoleName}
                    </div>
                </div>
            </div>

            <Image
                src={props.image}
                alt={'avatar'}
                width={40}
                height={40}
            />
        </div>
    )
}

function Header() {
    return (
        <header
            style={{
                background: '#ffffff',
                borderBottom: '1px solid #e6e6e6',
                padding: '0 24px',
                display: 'flex',
                alignItems: 'center',
                height: 64,
                position: 'relative',
                zIndex: 1,
                marginLeft: 240,
                boxShadow: '0px 20px 40px 0px #2A34390F',
                backdropFilter:'blur(12px)',
            }}
        >
            <div style={{display: 'flex', gap: '16px', flexDirection:'row', marginLeft: 'auto', alignItems: 'center'}}>
                <div style={{display: 'flex', flexDirection: 'row', gap: '32px', marginRight: '24px'}}>
                    <Image
                        src={'notification.svg'}
                        alt={'notification'}
                        width={20}
                        height={20}
                        className={'sidebar-icon'}
                    />
                    <Image
                        src={'question.svg'}
                        alt={'question'}
                        width={20}
                        height={20}
                        className={'sidebar-icon'}
                    />
                </div>

                <div style={{borderLeft: '1px solid #e6e6e6', paddingLeft: '32px'}}>
                    <UserPanel/>
                </div>
            </div>
        </header>
    )
}

interface ImageWithTextProps {
    image: string;
    text: string;
}

const ImageWithText: React.FC<ImageWithTextProps> = ({ image, text }) => {
    return (
        <div style={{ display: 'flex', flexDirection: 'row', textAlign: 'center', padding: '10px', paddingLeft: '20px' }}
             className={'sidebar-element'}
        >
            <Image
                src={image}
                alt={text}
                width={18}
                height={18}
                className={'sidebar-icon'}
            />
            <p style={{fontSize: '14px', margin: 0, marginLeft: '20px' }}>{text}</p>
        </div>
    )
}

interface sidebarElement {
    image: string,
    text: string,
    hideRoles: Roles[],
}

const upperSidebarData: sidebarElement[] = [
    {image: 'panel.svg', text: 'Панель', hideRoles: []},
    {image: 'tasks-list.svg', text: 'Задания', hideRoles: []},
    {image: 'mentors.svg', text: 'Менторы', hideRoles: [Roles.Student, Roles.Mentor]},
    {image: 'students.svg', text: 'Студенты', hideRoles: [Roles.Student, Roles.Mentor]},
    {image: 'options.svg', text: 'Настройки', hideRoles: []},
]

const lowerSidebarData: sidebarElement[] = [
    {image: 'faq.svg', text: 'FAQ', hideRoles: []},
    {image: 'exit.svg', text: 'Выход', hideRoles: []},
]

function Sidebar() {
    const role = getUserRole()

    const filteredUpperSidebarData = upperSidebarData.filter((sidebarElement) =>
        !sidebarElement.hideRoles.includes(role)
    )

    const filteredLowerSidebarData = lowerSidebarData.filter((sidebarElement) =>
        !sidebarElement.hideRoles.includes(role)
    )

    return (
        <aside
            style={{
                width: 240,
                background: '#f5f5f5',
                borderRight: '1px solid #e6e6e6',
                display: 'flex',
                flexDirection: 'column',
                position: 'fixed',
                top: 0,
                left: 0,
                bottom: 0,
                overflowY: 'auto',
                zIndex: 100,
            }}
        >
            <div style={{ paddingLeft: '24px', paddingTop: '24px', display: 'flex', flexDirection: 'column' }}>
                <div style={{ fontWeight: 900, fontSize: 18, letterSpacing: '-0.9px' }}>
                    FRONTEND HW
                </div>
                <div style={{ fontSize: 12, color: '#566166' }}>
                    Course Workspace
                </div>
            </div>

            <nav style={{marginTop: '32px', marginLeft: '8px'}}>
                {filteredUpperSidebarData.map((sidebarElement) => (
                    <div key={sidebarElement.image}>
                        <ImageWithText image={sidebarElement.image} text={sidebarElement.text} />
                    </div>
                ))}
            </nav>

            <nav style={{ marginTop: 'auto', marginLeft: '8px', marginBottom: '16px' }}>
                {filteredLowerSidebarData.map((sidebarElement) => (
                    <div key={sidebarElement.image}>
                        <ImageWithText image={sidebarElement.image} text={sidebarElement.text} />
                    </div>
                ))}
            </nav>
        </aside>
    )
}

export function LayoutContent({
                                  children,
                              }: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html>
        <body>
        <ThemeProvider theme="light">
            <Header />
            <Sidebar />
            <main
                style={{
                    marginLeft: 240,
                    padding: "24px",
                    minHeight: "calc(100vh)",
                }}
            >
                {children}
            </main>
        </ThemeProvider>
        </body>
        </html>
    )
}