import { Person } from '@gravity-ui/icons'
import { Session } from 'next-auth'

import { auth } from '@/features/auth/authSetup'
import { Roles } from '@/shared/types/roles'
import { LayoutContent } from '@/widgets/layout/layoutContent'
import { userRepository } from '@backend/users/repository'

import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const rolesMatcher = {
    STUDENT: Roles.Student,
    MENTOR: Roles.Mentor,
    ADMIN: Roles.Admin,
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const session = (await auth()) as Session

    let meData = null
    if (session?.user?.userId) {
        meData = await userRepository.findById(session.user.userId)
    }

    let user = null

    if (meData) {
        user = {
            name: '',
            role: rolesMatcher[meData.role],
            image: <Person className={'avatar-icon'} />,
        }
        if (meData.avatar) {
            user.image = (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                    src={meData.avatar}
                    height={40}
                    width={40}
                    alt="user-icon"
                />
            )
        }
        if (meData.name) {
            user.name = meData.name
        } else if (meData.login) {
            user.name = meData.login
        }
    }

    return (
        <html>
            <body>
                <LayoutContent user={user}>{children}</LayoutContent>
            </body>
        </html>
    )
}
