import { Person } from '@gravity-ui/icons'
import Image from 'next/image'
import { Session } from 'next-auth'
import { JSX } from 'react'

import { Roles } from '@/app/shared/types/roles'
import { LayoutContent } from '@/app/widgets/layout/layoutContent'
import { auth } from '@/auth/authSetup'
import { userRepository } from '@backend/users/repository'

import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export interface UserProps {
    name: string
    role: Roles
    image: JSX.Element
}

const rolesMatcher = {
    STUDENT: Roles.Student,
    MENTOR: Roles.Mentor,
    ADMIN: Roles.Admin,
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const session = (await auth()) as Session

    let meData = null
    if (session?.user?.userId) {
        meData = await userRepository.findById(session.user.userId)
    }

    let user = null

    if (meData) {
        user = {
            name: '',
            role: rolesMatcher[meData.role],
            image: <Person className={'avatar-icon'} />,
        }
        if (meData.avatar) {
            user.image = (
                <Image
                    src={meData.avatar}
                    width="40"
                    height="40"
                    alt="Аватар"
                    className={'avatar-icon'}
                />
            )
        }
        if (meData.name) {
            user.name = meData.name
        } else if (meData.login) {
            user.name = meData.login
        }
    }

    return (
        <html>
            <body>
                <LayoutContent user={user}>{children}</LayoutContent>
            </body>
        </html>
    )
}
